version: "3"
services:
  image_search_web:
    container_name: image_search_web
    image: ponponon/image_search_web:2023.09.07.1
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
    ports:
      - "6201:6201"
