apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: slave
  namespace: jenkins
  annotations:
    k8s.aliyun.com/eci-image-cache: "true" # 根据用户已有的镜像缓存，自动匹配镜像缓存。默认为false。
    k8s.aliyun.com/imc-enable-reuse: "true" # 开启镜像缓存复用。开启后，新创建的镜像缓存可以复用已有镜像缓存的镜像层，加快镜像缓存的制作速度。
spec:
  nodeSelector:
    type: virtual-kubelet
  tolerations:
  - key: virtual-kubelet.io/provider
    operator: Equal
    value: alibabacloud
    effect: NoSchedule
  containers:
  - image: jenkins/inbound-agent:4.3-4-jdk11
    imagePullPolicy: IfNotPresent
    name: jnlp
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    volumeMounts:
    - mountPath: /home/jenkins/agent
      name: workspace-cache
    workingDir: /home/jenkins/agent
    resources:
      requests:
        cpu: 3096m
        memory: 2560Mi
  - args:
    - "9999999"
    command:
    - sleep
    image: node:18.16
    imagePullPolicy: IfNotPresent
    name: node
    env:
    - name: pnpm
      value: /home/jenkins/agent/npm_global/bin/pnpm
    volumeMounts:
    - mountPath: /home/jenkins/agent
      name: workspace-cache
    workingDir: /home/jenkins/agent
  - args:
    - "9999999"
    command:
    - sleep
    image: docker:latest
    imagePullPolicy: IfNotPresent
    name: docker
    env:
    - name: DOCKER_HOST
      value: tcp://dind-service:2375
    - name: DOCKER_TLS_VERIFY
      value: ""
    volumeMounts:
      - mountPath: /home/jenkins/agent
        name: workspace-cache
    workingDir: /home/jenkins/agent
  volumes:
  - name: workspace-cache
    persistentVolumeClaim:
      claimName: workspace-cache
